
## 599 Third Exercise - Multivariate Case

### Zhiyi Wang

---
title: "Exercise-Multivariate"
author: "Zhiyi Wang"
date: "2019/3/10"
output: html_document
---
___________________________

<a id='part1'></a>

Exercises: <br>

- [Exercise 1](#ex1)
- [Exercise 2](#ex2)

___________________________


## Descriptive plots

<a id='ex1'></a>
<span style="color:red"> Exercise 1:<br> Improve one descriptive plot.
</span>


```{r, fig.width=20, fig.height=15, eval=FALSE}
library(openxlsx)
link2="https://github.com/EvansDataScience/data/raw/master/safeCitiesIndex.xlsx"

safe2=read.xlsx(link2)
head(safe2)

safe2A=melt(safe2,id.vars = 'city')
head(safe2A)

titleText1="Exercise1:The safety levels of cities in the world according to Digital, Health, Infrastructure, and Personal dimensions"
sourceText="Source:The Economist Intelligence Unit sponsored by NEC"

base  = ggplot(safe2A, aes(x = variable, y = value, group = city))

plot1 = base + geom_polygon(fill = 'gray50',col='orange') + coord_polar()

plot2 = plot1 + facet_wrap(~reorder(city,value, median, order=TRUE),ncol = 7)

plot3 = plot2 + theme(axis.text.x = element_text(size = 8),
                legend.position="none",
                strip.text = element_text(size = 20))

brdBkgnGrid=element_rect(fill = "white",colour = "red",
             size = 3,linetype = "dashed")

lineGrid=element_line(size = 3,linetype = 'solid',colour = "blue")

plot3+ theme(panel.background = brdBkgnGrid,
             panel.grid.major = lineGrid,
             plot.subtitle = element_text(size=15,hjust = 1),
             plot.title = element_text(size=20,hjust = 0.5)) + labs(title=titleText1,subtitle = sourceText)

```


## Inferential plots
<a id='ex2'></a>
<span style="color:red"> Exercise 2:<br> Improve one inferential plot.
</span>

<br>


```{r, eval=FALSE}
model1=lm(PERSONAL~HEALTH+INFRASTRUCTURE,data=safe2[,-1])
summary(model1)

library(dotwhisker)
library(broom)
library(dplyr)

model1_t = tidy(model1) %>% mutate(model = "Model 1") 
model1_t

model2=lm(PERSONAL~.,data=safe2[,-1]) 
summary(model2)

model2_t <- tidy(model2) %>% mutate(model = "Model 2")
```

```{r, eval=FALSE}
cut=median(safe2$PERSONAL)
safe2$PERSONAL_bi=ifelse(safe2$PERSONAL>cut,
                         1,0)
logit_PERSONAL = glm(PERSONAL_bi~ .,
                          data = safe2[,-c(1,5)],
                          family = "binomial")
summary(logit_PERSONAL)

library(margins)
margins_logit_PERSONAL = margins(logit_PERSONAL) 

marginalSummary=summary(margins_logit_PERSONAL)

as.data.frame(marginalSummary)

cplot(logit_PERSONAL,x="INFRASTRUCTURE") 

digi=cplot(logit_PERSONAL, "DIGITAL",draw = F)
head(digi)

base = ggplot(digi, aes(x = xvals)) 
p1= base + geom_ribbon(aes(ymin = lower, ymax = upper), 
                       fill = "grey90")
p2 = p1 + geom_line(aes(y = yvals)) 
p3= p2 + labs(title="Exercise2:Effect of DIGITAL index on PERSONAL index",
              subtitle = sourceText,
              x= "DIGITAL", y="Predicted Value")
p3 + theme(plot.subtitle = element_text(size=7,hjust = 1),
             plot.title = element_text(size=15,hjust = 0.5))
```

[Go to table of contents](#part1)


